### ISSUE TITLE
Home Assistant 2023.10 - If you have issues, please share here.

### ISSUE THREAD

**Issue by surakin** [libdyson-wg/ha-dyson#72] opened 2023-10-05 08:03 UTC
I could not see any error message on the home assistant logs :-\ even after reloading the integration several times.

I reverted to 2023.9.3 and it works again.

**Comment by dotvezz** [comment] 2023-10-05 16:13
I'll update my home assistant setup and validate/debug as needed. Thanks for the update.

While we're here, quick question: What method are you using to run Home Assistant? (Container, VM, Managed, etc)

**Comment by dotvezz** [comment] 2023-10-05 17:52
Interesting - one of my devices fails, but the rest are all working.

**Comment by surakin** [comment] 2023-10-05 18:41
> I'll update my home assistant setup and validate/debug as needed. Thanks for the update.
> 
> While we're here, quick question: What method are you using to run Home Assistant? (Container, VM, Managed, etc)

It's a docker container

I only have one device (pure cool link)

**Comment by dotvezz** [comment] 2023-10-05 18:45
```docker-home-assistant-1  | 2023-10-05 14:44:52.526 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for dyson_local
docker-home-assistant-1  | Traceback (most recent call last):
docker-home-assistant-1  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
docker-home-assistant-1  |     result = await component.async_setup_entry(hass, self)
docker-home-assistant-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-home-assistant-1  |   File "/config/custom_components/dyson_local/__init__.py", line 161, in async_setup_entry
docker-home-assistant-1  |     await hass.async_add_executor_job(
docker-home-assistant-1  | asyncio.exceptions.CancelledError: aiohttp connection lost
```

I was able to pull this from my docker logs. Not sure what this is, looking into it.

**Comment by dotvezz** [comment] 2023-10-05 18:52
Oh, I'm being silly - that error from my logs (and that one fan that fails) is just because it was unplugged.

I'm not able to reproduce your error at the moment, but I don't want to dismiss your issue at all. I'll keep looking into new issues from 2023.10 (I didn't have the presence of mind to check for possible bugs before it was released this time around, totally forgot it was coming) and see if I can find anything that helps.

In the meantime, let's see if we can get other reports from other users seeing similar issues on 2023.10. And of course, let me know if you want to try to upgrade and enable debug logging, maybe we'll get some information from another attempt.

**Comment by surakin** [comment] 2023-10-05 19:15
if I try 'enable debug logging' in the integration settings all I get is this
2023-10-05 21:13:06.580 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Living room' for dyson_local integration not ready yet: None; Retrying in background

**Comment by surakin** [comment] 2023-10-05 19:23
Odd.... suddenly, it's working 🤷 it didn't for an entire day before I rollbacked

**Comment by dotvezz** [comment] 2023-10-05 19:28
Hmmmm that's good but frustrating. Let's keep this issue open for the time being for others to possible post their issues if they have any (I'll rename it for discoverability).

If you have any further problems on 2023.10, feel free to pop back here and we can try to address it.

**Comment by surakin** [comment] 2023-10-05 19:29
Yes, I'll keep poking around to see if it's a network fluke or something else

**Comment by SumiS91** [comment] 2023-10-09 16:34
after updating HA to 2023.10 (installed on a raspberry pi with HA OS) and the addon to 1.2.0 my entities stoped working and everything was unavailable.
I restored my HA back to 2023.09, were i still had version 1.1.0 installed and it didn’t work either.
After that i upgraded HA back to the latest version, deleted the device completely and readded it (Dyson Pure Cool Link) while i was on version 1.1.0.
After the update to 1.2.0 it still works and everything is back to normal.

it‘s a really strange behavior and i couldn’t find anything in the logs why it happened, but maybe it helps somebody who has the same problem.

**Comment by amzaldua** [comment] 2023-10-10 09:58
Hello,

In version 2023.10.1 of HassIO, my Dyson TP09 integration works properly. However, I cannot set the oscillation angle. The available angles for my model are 45, 90, 180, and 350 degrees.

Regards,

**Comment by surakin** [comment] 2023-10-10 19:06
I just realized my pure cool link was having trouble connecting to my wifi network from before the 2023.10 upgrade 🤔 (something about 20mhz/40mhz wifi channels)
I'll see if future HA upgrades still show my issue now that I set it to 20mhz again

**Comment by dotvezz** [comment] 2023-10-25 01:46
Seems like there aren't any prevalent issues with the new Home Assistant releases. I'll close this issue, and we can track any individual issues as normal.

**Closed by dotvezz** 2023-10-25 01:46 UTC
