### ISSUE TITLE
Temp_celsius

### ISSUE THREAD

**Issue by UweEL** [libdyson-wg/ha-dyson#109] opened 2024-01-04 09:45 UTC
The following error message occurs after update to 2024.1.0:
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 09:12:10 (14 occurrences)
Last logged: 09:12:15

TEMP_CELSIUS was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
TIME_HOURS was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues

**Comment by codyc1515** [comment] 2024-01-10 03:35
Duplicate of #107

**Comment by dotvezz** [comment] 2024-01-10 03:41
@codyc1515 heh you beat me to it by mere minutes.

Also resolved in [v1.3.7](https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.3.7). But @UweEL please feel free to follow up on the #107 thread if you're having any further issues!

**Closed by dotvezz** 2024-01-10 03:41 UTC
