### ISSUE TITLE
Missing entities for Pure Cool Link fan TP-02

### ISSUE THREAD

**Issue by cinghialino** [libdyson-wg/ha-dyson#93] opened 2023-11-22 13:25 UTC
This new integration misses the following entities from the previous integration dyson_local when using a 

Pure Cool Link fan TP-02

- Pure Cool Link Volatile Organic Compounds
- Particulates

Can we please have them back? they are very useful for me. Thank you.
p.s the migration went flawlessly. Thank you for that.

**Comment by dotvezz** [comment] 2023-11-26 03:21
Hi @cinghialino! Sorry for the slow reply here, I think I'd typed up a response a few days ago but forgot to click the "Comment" button.

One of the interesting developments after forking this repo was a discovery that the VOC and Particulate sensors were being incorrectly handled by the previous integration. The contributor who added it initially was operating on the assumption that 0555 meant "555 ug/m3" when it actually meant "Index value of 5.55.". There's another recent discussion over here: https://github.com/libdyson-wg/ha-dyson/issues/89

I might want to try to find a way to help people discover this info. But anywho, tl;dr: it's not a bug, but a feature that the old sensors are no longer available.

I'll close this issue for now, but if you have reason to believe that the sensors need updating then please reopen so we can investigate and update the integration as needed! Right now we have limited access to devices. For example, I have an HP04 and HP07, but not HP09 so I rely on others to help me debug Formaldehyde stuff. And even different device revisions and firmware versions could behave differently.

**Closed by dotvezz** 2023-11-26 03:21 UTC
