### ISSUE TITLE
Failed to connect using Cloud + Local

### ISSUE THREAD

**Issue by splitsec2** [libdyson-wg/ha-dyson#9] opened 2023-04-08 23:01 UTC
I had my Dyson Pure Hot Cold (PT2-CA-HK******) connected through a YAML configuration (setup ~2.5 years ago), I am trying to move away from having things in my YAML so I removed that device from my configuration and installed this repo (local and cloud) through HACS.
HACS:
![image](https://user-images.githubusercontent.com/35583321/230745135-71f1c048-5e9e-47a9-a595-fa28db2dece5.png)
Integrations:
![image](https://user-images.githubusercontent.com/35583321/230745167-58f8bb67-8d35-4d52-b7ea-7e1685760bd0.png)

I was able to configure the cloud portion and log into my account (after I figured out that it sent an email with the code for entry).

But I am not able to "configure" or see my device inside HA.  When I click the configure on the local it asks for a host (optional), if I leave it blank it says "failed to connect"
![image](https://user-images.githubusercontent.com/35583321/230745226-975bc4e4-576c-4a41-baa9-9f77a96617ce.png)
if I enter the ip address of the device it also says Failed to connect.

This appears in the log:
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:169
First occurred: 4:01:17 PM (3 occurrences)
Last logged: 4:34:06 PM

Error setting up entry XXXXX@XXXXXXX.com (CA) for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 419, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by dotvezz** [comment] 2023-04-11 00:13
Hey @splitsec2! Thanks for raising this issue. I'm curious if your Home Assistant instance happens to be running in a Docker container or a VM.

I appreciate your posting the log entry, but it's sort of confusing. It looks like it's trying to set up a Camera using a core component, rather than trying to set up a Dyson fan using this custom repository's components? Is there anything if you search "dyson" in the logs?

**Comment by splitsec2** [comment] 2023-04-11 04:40
I agree it is confusing, I only have a pure heat &cool nothing with a camera attached. My home assistant is running in a VM. When I search for Dyson I get this one error

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/dyson_cloud/config_flow.py:95 
Integration: Dyson Cloud 
First occurred: April 8, 2023 at 3:58:46 PM (1 occurrences) 
Last logged: April 8, 2023 at 3:58:46 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/dyson_cloud/config_flow.py", line 95, in async_step_email_otp
    auth_info = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/libdyson/cloud/account.py", line 149, in _verify
    response = self.request(
  File "/usr/local/lib/python3.10/site-packages/libdyson/cloud/account.py", line 114, in request
    raise DysonInvalidAuth
libdyson.exceptions.DysonInvalidAuth

**Comment by dotvezz** [comment] 2023-04-11 14:32
Cool! Okay, that gives me two things to address:

## The Logs

That error looks like a login failure, which can happen for one of two reasons:

1. Bad credentials (password, OTP code, etc)
2. A quirk with the Dyson API

I'm happy to report that number 2 should be resolved by updating to the latest version of `ha-dyson-cloud` in your HACS setup.

## Automatic configuration

This project uses [zeroconf](https://pypi.org/project/zeroconf/) to auto-configure devices. But that technique can be blocked by most common network configurations for VMs and Docker containers. In order for auto-configuration to work reliably, your Home Assistant VM's NIC should at least be on the same subnet as your Dyson devices. Even if the VM host is on the same subnet, but the VM is using a network bridge, it most likely won't work.

## Manual configuration

You also said this:

> If I enter the ip address of the device it also says Failed to connect.

That's a bit more surprising! Fortunately for us, Dyson devices respond to ping. Are you able to ping your device from inside the VM?

**Comment by dotvezz** [comment] 2023-04-17 17:48
@splitsec2 just wanted to follow up and see if you were able to ping your device from your Home Assistant VM Guest.

**Comment by tr4j3dy** [comment] 2023-04-17 21:39
Unfortunately I'm facing the same issue as @splitsec2 

**Here is the result when adding via Dyson Local**

2023-04-17 14:19:19.636 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of libdyson-neon==0.10.2
2023-04-17 14:19:42.631 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Successfully parse WiFi information
2023-04-17 14:19:42.631 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Serial: NM7-US-HKA3102B
2023-04-17 14:19:42.631 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Device Type: 475
2023-04-17 14:19:42.631 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Device Type Name: Pure Cool Link
2023-04-17 14:19:52.723 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: 

**When setting up Dyson Cloud. I am given this and it seems like the integration was successful.**

2023-04-17 14:22:33.716 INFO (MainThread) [homeassistant.setup] Setting up dyson_cloud
2023-04-17 14:22:33.716 INFO (MainThread) [homeassistant.setup] Setup of domain dyson_cloud took 0.0 seconds
2023-04-17 14:22:34.179 INFO (MainThread) [homeassistant.components.camera] Setting up camera.dyson_cloud

**This also prompts immediate discovery of my Dyson Pure Cool. However, when configuring Dyson Local I am given this.**

2023-04-17 14:27:23.698 DEBUG (zeroconf-ServiceBrowser-_360eye_mqtt._tcp-_dyson_mqtt._tcp-141) [custom_components.dyson_local.config_flow] Found device at 10.10.8.22
2023-04-17 14:27:33.825 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: 
2023-04-17 14:27:33.828 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.lr_sound_2 is taking over 10 seconds
2023-04-17 14:27:33.828 WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
2023-04-17 14:27:33.828 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv is taking over 10 seconds

Seems like it's treating this as a camera entity?

**Some other information.**

10.10.8.22 is my Dyson. I am running in a container (host driver) but I've verified successful ping capability from container to Dyson.

Home Assistant 2023.4.4 / Frontend 20230411.1 - latest - Clean Deployment

Hopefully this information helps the both of you!

Thanks in advance!

**Comment by dotvezz** [comment] 2023-04-17 21:54
@tr4j3dy thanks for the info! Wow, this is _weird_: ```[homeassistant.components.camera] Setting up camera.dyson_cloud```. Are you not getting any information after the `Failed to connect to device:` lines? I'll need to investigate why it could be trying to treat _anything_ on `dyson_cloud` as a camera. 

Was your setup previously working on shenxn's repo, or is this a new-setup for you?

On the Container/Networking note: If you're using host networking for your container, that should bypass any of the caveats you'd normally see using zeroconf for auto-configuration. So that shouldn't be the cause of your issues. Thanks for confirming you can ping.

**Comment by dotvezz** [comment] 2023-04-17 22:06
Okay wow, yep. For some reason the cloud integration has some camera setup stuff, and it's been there ever since the beginning of the ha-cloud repository: https://github.com/libdyson-wg/ha-dyson-cloud/blob/main/custom_components/dyson_cloud/__init__.py#L26, https://github.com/libdyson-wg/ha-dyson-cloud/blob/main/custom_components/dyson_cloud/__init__.py#L61-L66

No idea why that's there, it seems totally unnecessary. Anyway, it also doesn't seem related to your bugs. For some reason, the camera stuff is totally expected... but I'm probably going to try to remove that in a release soon.

So the camera lines are a red herring - nice to no at least.

**Comment by dotvezz** [comment] 2023-04-17 22:10
Okay, a few more seconds of research before writing the confused comment above would have shown that it sets up camera entity capabilities specifically for the `DysonCleaningMapEntity` - apparently for the 360 Heurist robot vacuum

**Comment by tr4j3dy** [comment] 2023-04-19 02:40
This is a new setup. 

I can try to attempt to integrate this using shenxn's repo to see if I can replicate the issue.

To answer your question. There is no further debug after failed to connect and this is of course with the debug flags on in the configuration.yaml

Additionally I tried to add this manually by cloning into libdyson-neon. Was able to pull SN & Creds from Dyson. But experienced this when attempting the Dyson Local integration

```
2023-04-18 19:35:25.349 DEBUG (zeroconf-ServiceBrowser-_360eye_mqtt._tcp-_dyson_mqtt._tcp-133) [custom_components.dyson_local.config_flow] Found device at 10.10.8.22
2023-04-18 19:35:35.468 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: 
```

no further debug. I'll keep poking around and will let you know any additional information I receive. Thank you for the responses!

**Comment by dotvezz** [comment] 2023-04-19 16:26
> This is a new setup.
> 
> I can try to attempt to integrate this using shenxn's repo to see if I can replicate the issue.

Nice to know. I don't believe you'd see anything different on shenxn's repos, but if you'd like to check and see then by all means! I would appreciate the data, especially if it turns out my assumption is wrong.

In your log, it identifies your device as "Pure Cool Link" - is that accurate?

**Comment by dotvezz** [comment] 2023-05-09 16:57
@BigThunderSR thanks for confirming. Are you able to run the `get_devices.py` script from https://github.com/libdyson-wg/libdyson-neon and share the device information that it gives you? I think it should be device code 520, but I want to confirm.

Let me know if you need any help running that script by the way!

**Comment by dotvezz** [comment] 2023-07-11 12:33
Awesome! I actually don't think the new release had any fixes for this kind of issue, but let's take this win!

If you have any further issues, though, please don't hesitate to post here again.

**Closed by dotvezz** 2023-07-11 12:33 UTC
Labels: need more information
